package:
  name: ismrmrd-python-tools
  version: 0.1.0

source:
  git_url: https://github.com/ismrmrd/ismrmrd-python-tools.git
  git_rev: v0.1.0

requirements:
  build:
    - python
    - setuptools
    - pyxb
    - numpy
    - h5py
    - ismrmrd-python
    - nose

  run:
    - python
    - pyxb
    - numpy
    - h5py
    - ismrmrd-python

test:
  # Python imports
  imports:
    - ismrmrd

about:
  home: https://ismrmrd.github.io
  license: Public Domain
  summary: 'Python image reconstruction tools for the ISMRMRD raw data format'

