package:
  name: gadgetron-base
  version: "3.8.2"

source:
  git_url: https://github.com/gadgetron/gadgetron.git
  git_rev: v3.8.2

build:
  number: 0

requirements:
  build:
    - gcc [linux]
    - cmake
    - boost
    - python
    - fftw
    - armadillo
    - ace
    - gtest
    - dcmtk
    - numpy
    - ismrmrd-base

  run:
    - libgcc [linux]
    - boost
    - python
    - fftw
    - armadillo
    - ace
    - numpy
    - dcmtk
    - ismrmrd

about:
    home: http://gadgetron.github.io
    license: Public Domain
    summary: 'An open source framework for medical image reconstruction.'
