package:
  name: gadgetron
  version: 4.1.5

source:
  git_rev: dff06e87388c2930359efebabf98c804cb0f00e3
  git_url: https://github.com/gadgetron/gadgetron

requirements:
  build:
    - armadillo>=9.900.5
    - boost=1.76.0
    - cmake>=3.20.0
    - cuda-libraries-dev      # [linux64]
    - cuda-libraries          # [linux64]
    - cuda-runtime            # [linux64]
    - cuda-nvcc               # [linux64]
    - dcmtk=3.6.1
    - fftw=3.3.9
    - gcc_linux-64=9.4.0      # [linux64]
    - glew
    - gadgetron-python>=1.3.6
    - gmock>=1.10.0
    - gxx_linux-64=9.4.0      # [linux64]
    - gtest>=1.10.0
    - ismrmrd=1.7.1
    - ismrmrd-python>=1.9.6
    - libblas=*=*mkl
    - libcurl=7.79.1
    - libxml2=2.9.12
    - libxslt=1.1.33
    - mkl=2022.0.0            # [osx]
    - mkl-include=2022.0.0    # [osx]
    - mkl=2022.0.1            # [linux64]
    - mkl-include=2022.0.1    # [linux64]
    - ninja=1.10.2
    - nlohmann_json=3.10.4
    - numpy>=1.22.0
    - pugixml=1.11.4
    - pyfftw>=0.12.0
    - python>=3.9.0
    - range-v3>=0.11.0
    - rocksdb=6.13.3
    - sysroot_linux-64=2.17

  run:
    - armadillo=9.900.5
    - boost=1.76.0
    - cuda-libraries          # [linux64]
    - cuda-runtime            # [linux64]
    - dcmtk=3.6.1
    - fftw=3.3.9
    - gadgetron-python>=1.3.6
    - glew
    - ismrmrd=1.7.1
    - ismrmrd-python>=1.9.6
    - libblas=*=*mkl
    - libcurl=7.79.1
    - libxml2=2.9.12
    - libxslt=1.1.33
    - memkind=1.10.*
    - mkl=2022.0.1
    - numpy>=1.22.0
    - pugixml=1.11.4
    - pyfftw>=0.12.0
    - python>=3.9.0
    - rocksdb=6.13.3
    - sysroot_linux-64=2.17   # [linux64]

about:
  home:
  home: https://github.com/gadgetron/gadgetron
  summary: 'Gadgetron Image Reconstruction Framework'
  description: |
    Gadgetron reconstruction server with support libraries and example pipelines.
  dev_url: https://github.com/gadgetron/gadgetron
  doc_url: https://github.com/gadgetron/gadgetron
  doc_source_url: https://github.com/gadgetron/gadgetron/blob/master/README.md
