package:
  name: gadgetron
  version: "3.8.0"
    
source:
  git_url: https://github.com/gadgetron/gadgetron.git
  
requirements:
  build:
    - gcc [linux]
    - cmake
    - boost
    - fftw
    - armadillo
    - ace
    - numpy
    - ismrmrd
    - dcmtk
    - gtest

  run:
    - libgcc [linux]
    - boost
    - fftw
    - armadillo
    - ace
    - numpy
    - ismrmrd
    - dcmtk
    - ismrmrd-python
    - ismrmrd-python-tools
    - siemens_to_ismrmrd

about:
    home: http://gadgetron.github.io
    license: Public Domain
    summary: 'An open source framework for medical image reconstruction.'
