package:
  name: gadgetron
  version: "3.8.2"

source:
  git_url: https://github.com/gadgetron/gadgetron.git
  #git_rev: 3.8.2

requirements:
  build:
    #number: 0
    - gcc [linux]
    - cmake
    - boost
    - python
    - fftw
    - armadillo
    - ace
    - gtest
    - dcmtk
    - numpy
    - ismrmrd

  run:
    - libgcc [linux]
    - boost
    - python
    - fftw
    - armadillo
    - ace
    - numpy
    - dcmtk
    - ismrmrd
    - ismrmrd-python
    - ismrmrd-python-tools
    - siemens_to_ismrmrd

about:
    home: http://gadgetron.github.io
    license: Public Domain
    summary: 'An open source framework for medical image reconstruction.'
