package: 
  name: libiconv
  version: '1.14'

about:
  home: 'https://www.gnu.org/software/libiconv/'
  license: GPL

requirements:
  build:
    - pkg-config
    - libtool
  run:
    - pkg-config
    - libtool

source:
  fn: libiconv-1.14.tar.gz
  url: http://ftpmirror.gnu.org/libiconv/libiconv-1.14.tar.gz

test:
  commands: []
  files: []
  imports: []
  requires: []
