package:
  name: ismrmrd
  version: "1.3.0"
    
source:
  git_url: https://github.com/ismrmrd/ismrmrd.git

requirements:
  build:
    - cmake
    - boost
    - hdf5
    - fftw
    - libxslt [not win]
    - libxml2 [not win]

  run:
    - boost
    - hdf5
    - fftw
    - libxslt [not win]
    - libxml2 [not win]

about:
    home: http://ismrmrd.github.io
    license: Public Domain
    summary: 'ISMRM Raw Data Format'
