package:
  name: ismrmrd
  version: "1.3.0"
    
source:
  git_url: https://github.com/ismrmrd/ismrmrd.git
  

requirements:
  build:
    - cmake
    - hdf5
    - boost
    - fftw

  run:
    - hdf5
    - boost
    - fftw

about:
    home: http://ismrmrd.github.io
    license: Open Source
    summary: 'ISMRM Raw Data Format'
