package:
  name: ismrmrd
  version: 1.5.1

source:
  git_rev: a80c9595564b12fd1be91834247fab2c4ae37a91
  git_url: https://github.com/ismrmrd/ismrmrd

requirements:
  build:
    - boost=1.76.0
    - cmake>=3.20.0
    - fftw=3.3.9
    - gcc_linux-64>=9.0.0
    - gxx_linux-64>=9.0.0
    - git
    - hdf5=1.10.6
    - ninja=1.10.*
    - pugixml=1.11.4

  run:
    - boost=1.76.0
    - hdf5=1.10.6
    - pugixml=1.11.4
    - fftw=3.3.9

about:
  home: https://github.com/ismrmrd/ismrmrd
  license: MIT
  summary: 'ISMRM Raw Data Format (ISMRMRD)'
  description: |
    Libraries and tools for working with data in the ISMRM Raw Data (ISMRMRD or MRD).
  dev_url: https://github.com/ismrmrd/ismrmrd
  doc_url: https://github.com/ismrmrd/ismrmrd
  doc_source_url: https://github.com/ismrmrd/ismrmrd/blob/master/README.md