package:
  name: ismrmrd
  version: 1.5.0

source:
  git_rev: 15caac2dc1b7248553ff3cff8d6af3bcac1aea5a
  git_url: https://github.com/ismrmrd/ismrmrd

requirements:
  build:
    - boost=1.76.0
    - cmake>=3.20.0
    - fftw=3.3.9
    - gcc_linux-64>=9.0.0
    - gxx_linux-64>=9.0.0
    - git
    - hdf5=1.10.6
    - ninja=1.10.*
    - pugixml=1.11.4

  run:
    - boost=1.76.0
    - hdf5=1.10.6
    - pugixml=1.11.4
    - fftw=3.3.9

about:
  home: