package:
  name: ismrmrd
  version: "1.3.1"

build:
  number: 0

requirements:
  build:
    - ismrmrd-base 1.3.1
    - ismrmrd-python 1.3.1
    - ismrmrd-python-tools 0.1.0
    - siemens_to_ismrmrd 1.0.1
    #- philips_to_ismrmrd
    #- bruker_to_ismrmrd
    #- ge_to_ismrmrd

  run:
    - ismrmrd-base 1.3.1
    - ismrmrd-python 1.3.1
    - ismrmrd-python-tools 0.1.0
    - siemens_to_ismrmrd

about:
    home: http://gadgetron.github.io
    license: Public Domain
    summary: 'An open source framework for medical image reconstruction.'
