package:
  name: ismrmrd
  version: 1.7.0

source:
  git_rev: 31b3f1ed401761616fbf05df427bfa566fae06ae
  git_url: https://github.com/ismrmrd/ismrmrd

requirements:
  build:
    - boost=1.76.0
    - clang>=12.0.0        # [osx]
    - clangxx>=12.0.0      # [osx]
    - cmake>=3.20.0
    - fftw=3.3.9
    - gcc_linux-64>=9.0.0  # [linux64]
    - gxx_linux-64>=9.0.0  # [linux64]
    - git
    - hdf5=1.10.6
    - ninja=1.10.*

  run:
    - boost=1.76.0
    - hdf5=1.10.6
    - fftw=3.3.9

about:
  home: https://github.com/ismrmrd/ismrmrd
  license: MIT
  summary: 'ISMRM Raw Data Format (ISMRMRD)'
  description: |
    Libraries and tools for working with data in the ISMRM Raw Data (ISMRMRD or MRD).
  dev_url: https://github.com/ismrmrd/ismrmrd
  doc_url: https://github.com/ismrmrd/ismrmrd
  doc_source_url: https://github.com/ismrmrd/ismrmrd/blob/master/README.md
