package:
  name: cpr
  version: 1.7.2

source:
  git_rev: beb9e98806bb84bcc130a2cebfbcbbc6ce62b335
  git_url: https://github.com/libcpr/cpr

requirements:
  build:
    - clang>=13.0.1        # [osx]
    - clangxx>=13.0.1      # [osx]
    - cmake>=3.20.0
    - gcc_linux-64>=9.0.0  # [linux64]
    - gxx_linux-64>=9.0.0  # [linux64]
    - libcurl=7.79.1
    - ninja=1.10.*

  run:
    - libcurl=7.79.1

about:
  home: https://github.com/libcpr/cpr
  license: MIT
  summary: 'C++ Requests: Curl for People'
  description: |
    C++ Requests is a simple wrapper around libcurl inspired by the excellent Python Requests project.
  dev_url: https://github.com/libcpr/cpr
  doc_url: https://github.com/libcpr/cpr
  doc_source_url: https://github.com/libcpr/cpr/blob/master/README.md
