package: ismrmrd-python

platform:
  - linux-64

engine:
  - python=2.7
  - python=3.4

script:
  - conda config --add channels https://conda.anaconda.org/inati
  - conda build .

build_targets:
  - conda
