package:
  name: ismrmrd-python
  version: "1.3.1"

source:
  git_url: https://github.com/ismrmrd/ismrmrd-python.git
  git_rev: v1.3.1

requirements:
  build:
    - python
    - setuptools
    - pyxb
    - numpy
    - h5py
    - nose

  run:
    - python
    - pyxb
    - numpy
    - h5py

about:
  home: https://ismrmrd.github.io
  license: Public Domain
  summary: 'Python implementation of the ISMRMRD'

