package:
  name: siemens_to_ismrmrd
  version: 1.0.1.1

source:
  git_rev: 6d0ab3d3d0c8ade5c0526db1c6af9825008425ad
  git_url: https://github.com/ismrmrd/siemens_to_ismrmrd

requirements:
  build:
    - boost=1.76.0
    - cmake>=3.20.0
    - gcc_linux-64>=9.0.0
    - gxx_linux-64>=9.0.0
    - ismrmrd=1.5.1
    - libxml2=2.9.12
    - libxslt=1.1.33
    - ninja=1.10.*

  run:
    - ismrmrd=1.5.1
    - boost=1.76.0
    - libxml2=2.9.12
    - libxslt=1.1.33 

about:
  home: https://github.com/ismrmrd/siemens_to_ismrmrd
  license: MIT
  summary: 'ISMRM Raw Data Format (ISMRMRD)'
  description: |
    Siemens MR data to ISMRMRD (MRD) converter.
  dev_url: https://github.com/ismrmrd/siemens_to_ismrmrd
  doc_url: https://github.com/ismrmrd/siemens_to_ismrmrd
  doc_source_url: https://github.com/ismrmrd/siemens_to_ismrmrd/blob/master/README.md