package:
  name: siemens_to_ismrmrd
  version: 1.1.0

source:
  git_rev: 5bc4aedfb8b53c35d26dae0972bcdabdba512451
  git_url: https://github.com/ismrmrd/siemens_to_ismrmrd

requirements:
  build:
    - boost=1.76.0
    - clang>=12.0.0        # [osx]
    - clangxx>=12.0.0      # [osx]
    - cmake>=3.20.0
    - gcc_linux-64>=9.0.0  # [linux64] 
    - gxx_linux-64>=9.0.0  # [linux64]
    - ismrmrd=1.7.0
    - libxml2=2.9.12
    - libxslt=1.1.33 
    - ninja=1.10.*

  run:
    - ismrmrd=1.7.0
    - boost=1.76.0
    - libxml2=2.9.12
    - libxslt=1.1.33 

about:
  home:
