package:
  name: siemens_to_ismrmrd
  version: "1.0.0"
    
source:
  git_url: https://github.com/ismrmrd/siemens_to_ismrmrd.git
  
requirements:
  build:
    - cmake
    - ismrmrd

  run:
    - ismrmrd

about:
    home: http://ismrmrd.github.io
    license: Pubclic Domain
    summary: 'Converter from Siemens Raw MRI Data to ISMRM Raw Data Format'
