package:
    name: ace
    version: "6.3.2"

source:
    fn: ace-6.3.2.tar.gz
    url: http://download.dre.vanderbilt.edu/previous_versions/ACE-6.3.2.tar.gz
    md5: 294aa162b4e322323a5eafac599d4e04

about:
    home: http://www.dre.vanderbilt.edu/~schmidt/ACE.html
    summary: 'The Adaptive Communication Environment.'
