package:
  name: bruker_to_ismrmrd
  version: "0.5.0"
    
source:
  git_url: https://github.com/ismrmrd/bruker_to_ismrmrd.git
  git_rev: v0.5.0
  
requirements:
  build:
    - cmake
    - boost
    - ismrmrd

  run:
    - boost
    - ismrmrd

about:
    home: http://ismrmrd.github.io
    license: Pubclic Domain
    summary: 'Converter from Bruker Raw MRI Data to ISMRM Raw Data Format'
