package:
  name: pyxb
  version: 1.2.4

about: 
  home: 'http://pyxb.sourceforge.net'
  license: Apache Software License
  summary: Python XML Schema Bindings

requirements:
  build:
    - python
  run:
    - python

source:
  fn: PyXB-1.2.4.tar.gz
  md5: cea2ffde4a36ca88f76c687ee6549cfd
  url: https://pypi.python.org/packages/source/P/PyXB/PyXB-1.2.4.tar.gz

