package:
  name: mrd-storage-server
  version: 1.5.0

source:
  git_rev: v0.0.7
  git_url: https://github.com/ismrmrd/mrd-storage-server

requirements:
  build:
    - go-cgo=1.17.6

  run: {}

test:
  requires:
    - curl

about:
  home:
