package:
    name: gtest
    version: "1.7.0"

source:
    fn: gtest-1.7.0-zip
    url: https://googletest.googlecode.com/files/gtest-1.7.0.zip
    md5: 2d6ec8ccdf5c46b05ba54a9fd1d130d7

requirements:
    build:
      - cmake

about:
    home: https://code.google.com/p/googletest/
    summary: "Google's framework for writing C++ tests on a variety of platforms "

