package:
  name: gadgetron-python
  version: 1.3.6

source:
  git_rev: 57dfba04bc5b608a48a60527ee812200fde6ff50
  git_url: https://github.com/gadgetron/gadgetron-python

requirements:
  build:
    - python>=3.6
    - multimethod>=1.0
    - numpy>=1.5.1
    - ismrmrd-python>=1.9.5
    - pyfftw>=0.11.0

  run:
    - python>=3.6
    - multimethod>=1.0
    - numpy>=1.5.1
    - ismrmrd-python>=1.9.5
    - pyfftw>=0.11.0

about:
  home:
