package:
    name: armadillo
    version: "4.650"

source:
    fn: armadillo-4.650.4.tar.gz
    url: http://sourceforge.net/projects/arma/files/armadillo-4.650.4.tar.gz
    md5: e575dc01cf60e290a467c7c6d3171ef3

requirements:
    build:
      - cmake

about:
    home: http://arma.sourceforge.net
    license: Mozilla Public License 2.0
    summary: "C++ linear algebra library"

