package:
  name: ismrmrd-python
  version: "1.3.0"

source:
  git_url: https://github.com/ismrmrd/ismrmrd-python.git
  #git_rev: 1.3.0

requirements:
  build:
    #number: 0
    - python
    - setuptools
    - pyxb
    - numpy
    - h5py
    - nose

  run:
    - python
    - pyxb
    - numpy
    - h5py

about:
  home: https://ismrmrd.github.io
  license: Public Domain
  summary: 'Python implementation of the ISMRMRD'

