package:
  name: ismrmrd-python
  version: "1.3.0"

source:
  git_url: https://github.com/ismrmrd/ismrmrd-python.git
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ismrmrd = ismrmrd:main
    #
    # Would create an entry point called ismrmrd that calls ismrmrd.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyxb
    - numpy
    - h5py
    - nose

  run:
    - python
    - pyxb
    - numpy
    - h5py

test:
  # Python imports
  imports:
    - ismrmrd

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://ismrmrd.github.io
  license: Public Domain
  summary: 'Python implementation of the ISMRMRD'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
