package:
  name: ismrmrd-python
  version: 1.9.6

source:
  git_rev: c096dedfe8de59f52d1820e68abc34e649a74309
  git_url: https://github.com/ismrmrd/ismrmrd-python

requirements:
  build:
    - numpy>=1.22.0
    - h5py>=2.3
    - nose>=1.0
    - xsdata=21.12

  run:
    - xsdata=21.12
    - numpy>=1.22.0
    - h5py>=2.3

about:
  home: