package:
  name: ismrmrd-python
  version: 1.9.8

source:
  git_rev: v1.9.8
  git_url: https://github.com/ismrmrd/ismrmrd-python

requirements:
  build:
    - numpy>=1.22.0
    - h5py>=2.3
    - nose>=1.0
    - xsdata>=22.2

  run:
    - xsdata>=22.2
    - numpy>=1.22.0
    - h5py>=2.3

about:
  home:
