package:
    name: dcmtk
    version: "3.6.1"

source:
    fn: dcmtk-3.6.1.tar.gz
    url: http://dicom.offis.de/download/dcmtk/snapshot/dcmtk-3.6.1_20150629.tar.gz
    md5: 2faf73786fc638ae05fef0103cce0eea


requirements:
    build:
      - cmake
      - gcc >=4.7 [linux]
      - openssl
      - libpng
      - libtiff
      - libxml2
      - zlib

about:
    home: http://dicom.offis.de
    summary: "DCMTK is a collection of libraries and applications implementing large parts the DICOM standard"

