on:
  pull_request:
    branches:    
      - master
  push:
    branches:
      - master

jobs:
  build-conda-packages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test of workflow"