on:
  pull_request:
    branches:    
      - master
  push:
    branches:
      - master

jobs:
  build-conda-packages:
    strategy:
      matrix: [ubuntu-latest, macos-latest]
        os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gadgetron-conda-recipes
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
      - name: ${{ matrix.os }} conda conda packages build
        shell: bash -l {0}
        if: ${{ github.event_name == 'pull_request' }}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          ./build.sh --include-user-channel -p cpr -p gadgetron-python -p ismrmrd -p ismrmrd-python -p mrd-storage-server -p range-v3 -p siemens_to_ismrmrd
      # - name: Build and push conda packages
        # shell: bash -l {0}
        # if: ${{ github.event_name == 'push' }}
        # env:
          # ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        # run: |
          # ./build.sh --include-user-channel --token "$ANACONDA_TOKEN" --push
