on:
  pull_request:
    branches:    
      - master
  push:
    branches:
      - master

jobs:
  build-conda-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Testing conda install
        run: |
          $CONDA/bin/conda activate base
          conda build -h
          anaconda upload -h