on:
  pull_request:
    branches:    
      - master
  push:
    branches:
      - master

jobs:
  build-conda-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gadgetron-conda-recipes
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
      - name: Testing conda install
        shell: bash -l {0}
        run: |
          conda build -h
          anaconda upload -h